/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:Developer[MAX_PLAYERS];
new PlayerText:Admin[MAX_PLAYERS];

//Textdraws

//Player Textdraws
Developer[playerid] = CreatePlayerTextDraw(playerid, 300.000000, 6.000000, "~r~~h~93~g~~h~ 25~b~~h~~h~~h~ 35");
PlayerTextDrawFont(playerid, Developer[playerid], 1);
PlayerTextDrawLetterSize(playerid, Developer[playerid], 0.183332, 1.650001);
PlayerTextDrawTextSize(playerid, Developer[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Developer[playerid], 1);
PlayerTextDrawSetShadow(playerid, Developer[playerid], 0);
PlayerTextDrawAlignment(playerid, Developer[playerid], 1);
PlayerTextDrawColor(playerid, Developer[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, Developer[playerid], 255);
PlayerTextDrawBoxColor(playerid, Developer[playerid], 50);
PlayerTextDrawUseBox(playerid, Developer[playerid], 0);
PlayerTextDrawSetProportional(playerid, Developer[playerid], 1);
PlayerTextDrawSetSelectable(playerid, Developer[playerid], 0);

Admin[playerid] = CreatePlayerTextDraw(playerid, 502.000000, -1.000000, "~p~~h~ADMIN-DUTY");
PlayerTextDrawFont(playerid, Admin[playerid], 1);
PlayerTextDrawLetterSize(playerid, Admin[playerid], 0.170833, 1.250000);
PlayerTextDrawTextSize(playerid, Admin[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Admin[playerid], 1);
PlayerTextDrawSetShadow(playerid, Admin[playerid], 0);
PlayerTextDrawAlignment(playerid, Admin[playerid], 1);
PlayerTextDrawColor(playerid, Admin[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, Admin[playerid], 255);
PlayerTextDrawBoxColor(playerid, Admin[playerid], 50);
PlayerTextDrawUseBox(playerid, Admin[playerid], 0);
PlayerTextDrawSetProportional(playerid, Admin[playerid], 1);
PlayerTextDrawSetSelectable(playerid, Admin[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
