/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[14];

//Textdraws
PublicTD[0] = TextDrawCreate(311.000000, 139.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.600000, 23.800003);
TextDrawTextSize(PublicTD[0], 298.000000, 275.500000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], -1094795561);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(277.000000, 137.000000, "Repara firele");
TextDrawFont(PublicTD[1], 3);
TextDrawLetterSize(PublicTD[1], 0.308333, 1.500000);
TextDrawTextSize(PublicTD[1], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(299.000000, 188.000000, "_");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.600000, 0.300003);
TextDrawTextSize(PublicTD[2], 298.500000, 194.500000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 2);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], -65281);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(186.000000, 181.000000, "ld_pool:ball");
TextDrawFont(PublicTD[3], 4);
TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[3], 17.000000, 17.000000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -741092353);
TextDrawBackgroundColor(PublicTD[3], -16776961);
TextDrawBoxColor(PublicTD[3], 65396);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 1);

PublicTD[4] = TextDrawCreate(299.000000, 220.000000, "_");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.600000, 0.300003);
TextDrawTextSize(PublicTD[4], 298.500000, 194.500000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 2);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], -16776961);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(396.000000, 181.000000, "ld_pool:ball");
TextDrawFont(PublicTD[5], 4);
TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[5], 17.000000, 17.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], -741092353);
TextDrawBackgroundColor(PublicTD[5], -16776961);
TextDrawBoxColor(PublicTD[5], 65396);
TextDrawUseBox(PublicTD[5], 0);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 1);

PublicTD[6] = TextDrawCreate(186.000000, 214.000000, "ld_pool:ball");
TextDrawFont(PublicTD[6], 4);
TextDrawLetterSize(PublicTD[6], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[6], 17.000000, 17.000000);
TextDrawSetOutline(PublicTD[6], 1);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -741092353);
TextDrawBackgroundColor(PublicTD[6], -16776961);
TextDrawBoxColor(PublicTD[6], 65396);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 1);

PublicTD[7] = TextDrawCreate(396.000000, 214.000000, "ld_pool:ball");
TextDrawFont(PublicTD[7], 4);
TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[7], 17.000000, 17.000000);
TextDrawSetOutline(PublicTD[7], 1);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -741092353);
TextDrawBackgroundColor(PublicTD[7], -16776961);
TextDrawBoxColor(PublicTD[7], 65396);
TextDrawUseBox(PublicTD[7], 0);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 1);

PublicTD[8] = TextDrawCreate(299.000000, 251.000000, "_");
TextDrawFont(PublicTD[8], 1);
TextDrawLetterSize(PublicTD[8], 0.600000, 0.300003);
TextDrawTextSize(PublicTD[8], 298.500000, 194.500000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 2);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 1097458175);
TextDrawUseBox(PublicTD[8], 1);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(396.000000, 244.000000, "ld_pool:ball");
TextDrawFont(PublicTD[9], 4);
TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[9], 17.000000, 17.000000);
TextDrawSetOutline(PublicTD[9], 1);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], -741092353);
TextDrawBackgroundColor(PublicTD[9], -16776961);
TextDrawBoxColor(PublicTD[9], 65396);
TextDrawUseBox(PublicTD[9], 0);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 1);

PublicTD[10] = TextDrawCreate(187.000000, 244.000000, "ld_pool:ball");
TextDrawFont(PublicTD[10], 4);
TextDrawLetterSize(PublicTD[10], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[10], 17.000000, 17.000000);
TextDrawSetOutline(PublicTD[10], 1);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 1);
TextDrawColor(PublicTD[10], -741092353);
TextDrawBackgroundColor(PublicTD[10], -16776961);
TextDrawBoxColor(PublicTD[10], 65396);
TextDrawUseBox(PublicTD[10], 0);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 1);

PublicTD[11] = TextDrawCreate(299.000000, 281.000000, "_");
TextDrawFont(PublicTD[11], 1);
TextDrawLetterSize(PublicTD[11], 0.600000, 0.300003);
TextDrawTextSize(PublicTD[11], 298.500000, 194.500000);
TextDrawSetOutline(PublicTD[11], 1);
TextDrawSetShadow(PublicTD[11], 0);
TextDrawAlignment(PublicTD[11], 2);
TextDrawColor(PublicTD[11], -1);
TextDrawBackgroundColor(PublicTD[11], 255);
TextDrawBoxColor(PublicTD[11], 1433087999);
TextDrawUseBox(PublicTD[11], 1);
TextDrawSetProportional(PublicTD[11], 1);
TextDrawSetSelectable(PublicTD[11], 0);

PublicTD[12] = TextDrawCreate(187.000000, 274.000000, "ld_pool:ball");
TextDrawFont(PublicTD[12], 4);
TextDrawLetterSize(PublicTD[12], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[12], 17.000000, 17.000000);
TextDrawSetOutline(PublicTD[12], 1);
TextDrawSetShadow(PublicTD[12], 0);
TextDrawAlignment(PublicTD[12], 1);
TextDrawColor(PublicTD[12], -741092353);
TextDrawBackgroundColor(PublicTD[12], -16776961);
TextDrawBoxColor(PublicTD[12], 65396);
TextDrawUseBox(PublicTD[12], 0);
TextDrawSetProportional(PublicTD[12], 1);
TextDrawSetSelectable(PublicTD[12], 1);

PublicTD[13] = TextDrawCreate(397.000000, 274.000000, "ld_pool:ball");
TextDrawFont(PublicTD[13], 4);
TextDrawLetterSize(PublicTD[13], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[13], 17.000000, 17.000000);
TextDrawSetOutline(PublicTD[13], 1);
TextDrawSetShadow(PublicTD[13], 0);
TextDrawAlignment(PublicTD[13], 1);
TextDrawColor(PublicTD[13], -741092353);
TextDrawBackgroundColor(PublicTD[13], -16776961);
TextDrawBoxColor(PublicTD[13], 65396);
TextDrawUseBox(PublicTD[13], 0);
TextDrawSetProportional(PublicTD[13], 1);
TextDrawSetSelectable(PublicTD[13], 1);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
