/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[10];

//Textdraws
PublicTD[0] = TextDrawCreate(321.000000, 149.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.495833, 22.300003);
TextDrawTextSize(PublicTD[0], 308.500000, 380.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 1097458055);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(180.000000, 150.000000, "Preview_Model");
TextDrawFont(PublicTD[1], 5);
TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[1], 57.500000, 70.000000);
TextDrawSetOutline(PublicTD[1], 0);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 0);
TextDrawBoxColor(PublicTD[1], 0);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 1);
TextDrawSetPreviewModel(PublicTD[1], 19630);
TextDrawSetPreviewRot(PublicTD[1], -10.000000, 3.000000, -22.000000, 0.699999);
TextDrawSetPreviewVehCol(PublicTD[1], 0, 0);

PublicTD[2] = TextDrawCreate(310.000000, 210.000000, "Preview_Model");
TextDrawFont(PublicTD[2], 5);
TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[2], 57.500000, 70.000000);
TextDrawSetOutline(PublicTD[2], 0);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 0);
TextDrawBoxColor(PublicTD[2], 0);
TextDrawUseBox(PublicTD[2], 0);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 1);
TextDrawSetPreviewModel(PublicTD[2], 19630);
TextDrawSetPreviewRot(PublicTD[2], -10.000000, 3.000000, -22.000000, 0.699999);
TextDrawSetPreviewVehCol(PublicTD[2], 0, 0);

PublicTD[3] = TextDrawCreate(190.000000, 250.000000, "Preview_Model");
TextDrawFont(PublicTD[3], 5);
TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[3], 57.500000, 70.000000);
TextDrawSetOutline(PublicTD[3], 0);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 0);
TextDrawBoxColor(PublicTD[3], 0);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 1);
TextDrawSetPreviewModel(PublicTD[3], 19630);
TextDrawSetPreviewRot(PublicTD[3], -10.000000, 3.000000, -22.000000, 0.699999);
TextDrawSetPreviewVehCol(PublicTD[3], 0, 0);

PublicTD[4] = TextDrawCreate(426.000000, 150.000000, "_");
TextDrawFont(PublicTD[4], 2);
TextDrawLetterSize(PublicTD[4], 0.600000, 22.149997);
TextDrawTextSize(PublicTD[4], 297.000000, -3.500000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 2);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], -121);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(437.000000, 150.000000, "Ai prins ~b~~h~99 ~w~de pesti");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.191667, 0.650000);
TextDrawTextSize(PublicTD[5], 585.000000, 17.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], -1);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 0);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);

PublicTD[6] = TextDrawCreate(433.000000, 164.000000, "Esti un pescar ~r~adevarat");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.191667, 0.650000);
TextDrawTextSize(PublicTD[6], 585.000000, 17.000000);
TextDrawSetOutline(PublicTD[6], 1);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);

PublicTD[7] = TextDrawCreate(462.000000, 200.000000, "ld_drv:ribb");
TextDrawFont(PublicTD[7], 4);
TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[7], -32.500000, 19.000000);
TextDrawSetOutline(PublicTD[7], 1);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 50);
TextDrawUseBox(PublicTD[7], 1);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);

PublicTD[8] = TextDrawCreate(473.000000, 202.000000, "ld_drv:ribb");
TextDrawFont(PublicTD[8], 4);
TextDrawLetterSize(PublicTD[8], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[8], 37.500000, 18.000000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 50);
TextDrawUseBox(PublicTD[8], 1);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(454.000000, 180.000000, "ld_drv:golfly");
TextDrawFont(PublicTD[9], 4);
TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[9], 33.500000, 43.500000);
TextDrawSetOutline(PublicTD[9], 1);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], -1);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], 50);
TextDrawUseBox(PublicTD[9], 1);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
