new city_skins[] = {147, 186, 187, 295, 17, 91, 93, 141, 150};

new attach_city_model[] = {19904,19142,19515,18636,19161,19162,19521,19098,19200,19776,19777,18875,19942};
new bort_list_city[4] = {19834, 1238, 1228, 1459};

new attach_city_name[][] =
{
	"Colete laranja",
	"Colete à prova de balas preto",
	"Colete à prova de balas cinza",
	"Boné de polícia #1",
	"Boné de polícia #2",
	"Boné de polícia #3",
	"Boné de polícia",
	"Chapéu de polícia",
	"Capacete de motocicleta da polícia",
	"Crachá do FBI",
	"Logotipo do FBI",
	"Pager",
	"Walkie-talkie"
};

new bort_names_city[4][32] =
{
	"Fita",
	"Cone",
	"Barreira",
	"Barreira 2"
};
